version: '3.1'

services: 
  
  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks: 
      - local-network

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    networks: 
      - local-network
    depends_on: 
      - "mongo"  

networks: 
  local-network:
    driver: bridge