version: '3.1'

services: 
  
  my-awesome-series:
    image: fjunqueira/my-awesome-series
    build: '.'
    ports:
      - "80:3000"
    environment:
      MONGODB: 'mongodb://mongo/my-awesome-series'
    networks: 
      - local-network      
    depends_on: 
      - mongo

  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks: 
      - local-network

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    networks: 
      - local-network
    depends_on: 
      - "mongo"  

networks: 
  local-network:
    driver: bridge